package bootstrap

// RegisterAll wires all MF service implementations into the registry.
// THIS FILE IS AUTO-GENERATED by the injector service using Gonja templates.
// Do not edit manually — re-run the injector to regenerate.
func RegisterAll() {
	// placeholder — no implementations registered yet
	// run: cd service-injector && go run ./cmd/injector
}
