package main

import (
	"log"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"project1-mf-backend/internal/bootstrap"
	"project1-mf-backend/internal/handler"
)

func main() {
	// Step 1: Register all injected implementations.
	// bootstrap.go is auto-generated by the injector service.
	// It wires project2-mf-implementations into this project's registry.
	bootstrap.RegisterAll()

	// Step 2: Setup Echo
	e := echo.New()
	e.HideBanner = false

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())
	e.Use(middleware.RequestID())
	e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: []string{"*"},
		AllowMethods: []string{http.MethodGet, http.MethodPost, http.MethodPut, http.MethodDelete},
		AllowHeaders: []string{echo.HeaderOrigin, echo.HeaderContentType, echo.HeaderAccept, echo.HeaderAuthorization},
	}))

	// Step 3: Register routes
	mfHandler := handler.NewMFHandler()
	mfHandler.RegisterRoutes(e)

	// Health check
	e.GET("/health", func(c echo.Context) error {
		return c.JSON(http.StatusOK, map[string]string{
			"status":  "ok",
			"service": "SEBI MF API",
		})
	})

	// Step 4: Start server
	log.Println("SEBI MF Backend starting on :8080")
	log.Println("Routes:")
	log.Println("  POST   /mutualfund          → MFCreate")
	log.Println("  POST   /mutualfund/transfer → MFTransfer")
	log.Println("  PUT    /mutualfund          → MFUpdate")
	log.Println("  DELETE /mutualfund          → MFDelete")

	if err := e.Start(":8080"); err != nil && err != http.ErrServerClosed {
		log.Fatalf("Echo server error: %v", err)
	}
}
